import { Project, ComponentInstance } from '../contexts/ProjectContext';

export interface GeneratedFiles {
  indexHtml: string;
  stylesCss: string;
  appJs: string;
}

/**
 * ProjectCodeGenerator.generateWebAppFiles()
 * Generates a minimal, self-contained web app (HTML/CSS/JS) from the current Project model.
 * - Absolute positioning based on component.styles (left, top, width, height)
 * - Basic components mapped to native HTML equivalents for portability
 * - Embeds project and blueprints into window.Anvil for simple runtime access
 * - Provides a mock LLM stub for demonstration in exported builds
 */
export function generateWebAppFiles(project: Project): GeneratedFiles {
  const bodyContent = renderProjectComponents(project);
  const indexHtml = generateIndexHtml(project, bodyContent);
  const stylesCss = generateStylesCss();
  const appJs = generateAppJs(project);
  return { indexHtml, stylesCss, appJs };
}

function generateIndexHtml(project: Project, bodyContent: string): string {
  const appTitle = escapeHtml(project?.metadata?.name || 'Anvil App');
  const appDescription = escapeHtml(project?.metadata?.description || 'An application generated by Anvil');

  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '  <head>',
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `    <title>${appTitle}</title>`,
    '    <link rel="stylesheet" href="styles.css" />',
    '  </head>',
    '  <body>',
    '    <div class="app-container">',
    `      <header class="app-header"><h1>${appTitle}</h1><p>${appDescription}</p></header>`,
    '      <main class="app-main" id="app-root">',
    bodyContent,
    '      </main>',
    '    </div>',
    '    <script src="app.js"></script>',
    '  </body>',
    '</html>',
    ''
  ].join('\n');
}

function generateStylesCss(): string {
  return [
    'html, body { margin: 0; padding: 0; height: 100%; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; }',
    '.app-container { min-height: 100vh; background: #0f1115; color: #e5e7eb; }',
    '.app-header { padding: 14px 18px; border-bottom: 1px solid #1f2937; }',
    '.app-header h1 { margin: 0 0 6px 0; font-size: 20px; }',
    '.app-header p { margin: 0; color: #9ca3af; font-size: 13px; }',
    '.app-main { position: relative; min-height: calc(100vh - 64px); }',
    '.ui-component { position: absolute; box-sizing: border-box; }',
    '.ui-button { background-color: #2563eb; color: #fff; border: none; padding: 8px 14px; border-radius: 6px; cursor: pointer; }',
    '.ui-button.primary { background-color: #1d4ed8; }',
    '.ui-input { border: 1px solid #374151; background: #111827; color: #e5e7eb; padding: 8px 10px; border-radius: 6px; min-width: 120px; }',
    '.ui-label { padding: 6px 10px; color: #e5e7eb; }',
    '.ui-checkbox { display: inline-flex; align-items: center; gap: 8px; }',
    '.ui-dropdown { border: 1px solid #374151; background: #111827; color: #e5e7eb; padding: 8px 10px; border-radius: 6px; min-width: 120px; }',
    '.ui-container { border: 1px dashed #374151; border-radius: 8px; padding: 10px; background: #0b0d12; }',
    '.component-label { position: absolute; top: -18px; left: 0; font-size: 11px; color: #9ca3af; }',
    ''
  ].join('\n');
}

function generateAppJs(project: Project): string {
  const safeProject = JSON.stringify(project || {}, null, 2);

  return [
    '// Generated by Anvil ProjectCodeGenerator',
    '(function(){',
    '  try {',
    `    window.Anvil = window.Anvil || {};`,
    `    window.Anvil.project = ${safeProject};`,
    '    window.Anvil.blueprints = (window.Anvil.project && window.Anvil.project.blueprints) ? window.Anvil.project.blueprints : [];',
    '',
    '    // Minimal event bus for exported apps',
    '    window.Anvil.triggerEvent = function(eventType, payload) {',
    '      console.log("[Anvil] Event:", eventType, payload);',
    '    };',
    '',
    '    // Mock LLM interface for exported builds',
    '    window.Anvil.LLM = {',
    '      prompt: async function(promptText) {',
    '        console.log("[Anvil] LLM prompt:", promptText);',
    '        // Replace with real provider integration in production builds',
    '        return "Mock response to: " + String(promptText);',
    '      }',
    '    };',
    '',
    '    // Wire basic component events',
    '    document.addEventListener("DOMContentLoaded", function(){',
    '      // Buttons -> "onClick"',
    '      document.querySelectorAll("[data-component-type=\\"button\\"]").forEach(function(el){',
    '        el.addEventListener("click", function(){',
    '          window.Anvil.triggerEvent("onClick", { componentId: el.getAttribute("data-component-id") });',
    '        });',
    '      });',
    '',
    '      // Inputs -> "onChange"',
    '      document.querySelectorAll("[data-component-type=\\"textinput\\"] input").forEach(function(input){',
    '        input.addEventListener("input", function(){',
    '          window.Anvil.triggerEvent("onChange", { componentId: input.closest("[data-component-id]").getAttribute("data-component-id"), value: input.value });',
    '        });',
    '      });',
    '',
    '      // Dropdowns -> "onChange"',
    '      document.querySelectorAll("[data-component-type=\\"dropdown\\"] select").forEach(function(sel){',
    '        sel.addEventListener("change", function(){',
    '          window.Anvil.triggerEvent("onChange", { componentId: sel.closest("[data-component-id]").getAttribute("data-component-id"), value: sel.value });',
    '        });',
    '      });',
    '',
    '      // Checkboxes -> "onChange"',
    '      document.querySelectorAll("[data-component-type=\\"checkbox\\"] input[type=checkbox]").forEach(function(cb){',
    '        cb.addEventListener("change", function(){',
    '          window.Anvil.triggerEvent("onChange", { componentId: cb.closest("[data-component-id]").getAttribute("data-component-id"), checked: cb.checked });',
    '        });',
    '      });',
    '    });',
    '',
    '  } catch (err) {',
    '    console.error("[Anvil] Generated runtime error:", err);',
    '  }',
    '})();',
    ''
  ].join('\n');
}

function renderProjectComponents(project: Project): string {
  const comps = Array.isArray(project?.components) ? project.components : [];
  return comps.map(renderComponentTree).join('\n');
}

function renderComponentTree(comp: ComponentInstance): string {
  const style = toInlineStyle(comp?.styles || {});
  const label = escapeHtml(comp?.name || comp?.type || 'Component');
  const inner = renderComponent(comp);
  const children = Array.isArray(comp?.children) ? comp.children.map(renderComponentTree).join('\n') : '';

  return [
    `<div class="ui-component" data-component-id="${escapeHtml(comp.id)}" data-component-type="${escapeHtml(comp.type)}" style="${style}">`,
    `  <div class="component-label">${label}</div>`,
    `  ${inner}`,
    `  ${children}`,
    `</div>`
  ].join('\n');
}

function renderComponent(comp: ComponentInstance): string {
  const t = (comp?.type || '').toLowerCase();
  const props = comp?.props || {};

  switch (t) {
    case 'button': {
      const text = escapeHtml(String(props?.text ?? 'Button'));
      const primary = !!props?.primary;
      const cls = primary ? 'ui-button primary' : 'ui-button';
      return `<button class="${cls}">${text}</button>`;
    }
    case 'textinput': {
      const placeholder = escapeHtml(String(props?.placeholder ?? 'Enter text'));
      const label = escapeHtml(String(props?.label ?? ''));
      const multiline = !!props?.multiline;
      const inputEl = multiline
        ? `<textarea class="ui-input" placeholder="${placeholder}"></textarea>`
        : `<input class="ui-input" type="text" placeholder="${placeholder}" />`;
      return label ? `<label class="ui-label">${label}</label>\n${inputEl}` : inputEl;
    }
    case 'label': {
      const text = escapeHtml(String(props?.text ?? 'Label'));
      return `<div class="ui-label">${text}</div>`;
    }
    case 'checkbox': {
      const label = escapeHtml(String(props?.label ?? 'Checkbox'));
      const checked = !!props?.checked ? 'checked' : '';
      return `<label class="ui-checkbox"><input type="checkbox" ${checked} /> <span>${label}</span></label>`;
    }
    case 'dropdown': {
      const label = escapeHtml(String(props?.label ?? 'Dropdown'));
      const options = coerceDropdownOptions(props?.options);
      const opts = options.map(o => `<option value="${escapeHtml(String(o.key))}">${escapeHtml(String(o.text))}</option>`).join('');
      return [
        label ? `<label class="ui-label">${label}</label>` : '',
        `<select class="ui-dropdown">${opts}</select>`
      ].join('\n');
    }
    case 'image': {
      const src = escapeHtml(String(props?.src ?? 'https://via.placeholder.com/150'));
      const alt = escapeHtml(String(props?.alt ?? 'Image'));
      const width = Number(props?.width ?? 150);
      const height = Number(props?.height ?? 150);
      return `<img src="${src}" alt="${alt}" width="${width}" height="${height}" />`;
    }
    case 'container': {
      const title = escapeHtml(String(props?.title ?? 'Container'));
      const showTitle = !!props?.showTitle;
      return [
        `<div class="ui-container">`,
        showTitle ? `  <div style="margin-bottom:8px;font-weight:600;">${title}</div>` : '',
        `</div>`
      ].join('\n');
    }
    default: {
      // Fallback
      return `<div class="ui-label">Unknown component: ${escapeHtml(comp.type)}</div>`;
    }
  }
}

function coerceDropdownOptions(options: any): Array<{ key: string; text: string }> {
  try {
    if (typeof options === 'string') {
      const arr = JSON.parse(options);
      if (Array.isArray(arr)) return arr;
    } else if (Array.isArray(options)) {
      return options;
    }
  } catch {
    // ignore
  }
  return [
    { key: 'option1', text: 'Option 1' },
    { key: 'option2', text: 'Option 2' }
  ];
}

function toInlineStyle(styles: Record<string, any>): string {
  if (!styles || typeof styles !== 'object') return '';
  const cssEntries: string[] = [];
  for (const [key, value] of Object.entries(styles)) {
    if (value === undefined || value === null || value === '') continue;
    const cssKey = camelToKebab(key);
    // Ensure numeric values that are meant to be px get px units if missing
    let cssVal: string = String(value);
    if (typeof value === 'number' && unitlessCssProps.indexOf(cssKey) === -1) {
      cssVal = `${value}px`;
    }
    cssEntries.push(`${cssKey}:${cssVal}`);
  }
  return cssEntries.join(';');
}

const unitlessCssProps = [
  'z-index', 'opacity', 'flex', 'font-weight', 'line-height'
];

function camelToKebab(key: string): string {
  return key.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
}

function escapeHtml(input: string): string {
  return String(input)
    .replace(/&/g, '&')
    .replace(/</g, '<')
    .replace(/>/g, '>')
    .replace(/"/g, '"');
}